@startsalt
skinparam Backgroundcolor lightblue
{

    {^
        [<color:brown>  ◴  ] |   | [<color:green>  ✔  ] |   | [  ⚙  ]
    }



    {SI
        . Task 1
        . ├───   Subtask 1.1
        . └───   Subtask 1.2
        .          ├───   Subtask 1.2.1   
        .          └───   Subtask 1.2.2   
        . Task 2
        . Task 3
        . Task 4
    }



    {^
        | [<color:blue>  ▶  ] |   | [<color:green>  +  ] |    | [<color:red>  ✗  ] |
    }
}
@endsalt